### ISSUE TITLE
[BUG] Android: Fix crash in GeofenceMonitor

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#139]
**Describe the bug**
Fix crash in Android reported via firebase console [here](https://console.firebase.google.com/project/rokwire-mvp01-dev/crashlytics/app/android:edu.illinois.rokwire/issues/388379441e4fce143f428df45da76ca0?time=last-ninety-days&sessionEventKey=5F8BA10802BE00014F3559A0EE450439_1463219258600403623).

**StackTrace**
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.content.ComponentName.<init>(ComponentName.java:128)
       at android.content.Intent.<init>(Intent.java:4910)
       at org.altbeacon.beacon.BeaconManager.bind(BeaconManager.java:424)
       at edu.illinois.rokwire.geofence.GeofenceMonitor.initBeaconManager(GeofenceMonitor.java:403)
       at edu.illinois.rokwire.geofence.GeofenceMonitor.onLocationPermissionGranted(GeofenceMonitor.java:100)
       at edu.illinois.rokwire.MainActivity$1.onResult(MainActivity.java:270)
       at edu.illinois.rokwire.MainActivity.onRequestPermissionsResult(MainActivity.java:133)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7274)
       at android.app.Activity.dispatchActivityResult(Activity.java:7126)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4219)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4266)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1615)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6393)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Devices**
Devices with Android 6 and 7.

**Comment by dobromirdobrev** [comment]
Fixed in version 2.3.13
