### ISSUE TITLE
[BUG] Android: Prevent crash in PollBleReceiver

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#144]
**Describe the bug**
Prevent crash in Android reported via firebase console [here](https://console.firebase.google.com/project/rokwire-mvp01-dev/crashlytics/app/android:edu.illinois.rokwire/issues/44e13f1138b37ce879cb55c37e8dbb2b?time=last-ninety-days&sessionEventKey=5F99E44503380001701842486D755C25_1467235797303870950).

**StackTrace**

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver edu.illinois.rokwire.poll.scan.PollBleReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=edu.illinois.rokwire/.poll.PollBleClient (has extras) }: app is in background uid UidRecord{916a162 u0a319 RCVR bg:+7m39s208ms idle change:uncached procs:1 seq(1185,1185,1185)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3614)
       at android.app.ActivityThread.access$1300(ActivityThread.java:213)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=edu.illinois.rokwire/.poll.PollBleClient (has extras) }: app is in background uid UidRecord{916a162 u0a319 RCVR bg:+7m39s208ms idle change:uncached procs:1 seq(1185,1185,1185)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1592)
       at android.app.ContextImpl.startService(ContextImpl.java:1547)
       at android.content.ContextWrapper.startService(ContextWrapper.java:664)
       at android.content.ContextWrapper.startService(ContextWrapper.java:664)
       at edu.illinois.rokwire.poll.scan.PollBleReceiver.onReceive(PollBleReceiver.java:70)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3605)
       at android.app.ActivityThread.access$1300(ActivityThread.java:213)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by dobromirdobrev** [comment]
The exception is caught. Currently there is nothing we can do as this is know issue for devices running Android 9 and above. https://issuetracker.google.com/issues/113122354
