### ISSUE TITLE
[BUG] Android: Fix crash in GeofenceBroadcastReceiver

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#2341]
Fix reported crash in Firebase Crashlytics console:

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver edu.illinois.rokwire.geofence.GeofenceBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "edu.illinois.rokwire.geofence.GeofenceBroadcastReceiver" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/base.apk", zip file "/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.arm64_v8a.apk", zip file "/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.en.apk", zip file "/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.ko.apk", zip file "/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.xxxhdpi.apk"],nativeLibraryDirectories=[/data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/lib/arm64, /data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/base.apk!/lib/arm64-v8a, /data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.en.apk!/lib/arm64-v8a, /data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.ko.apk!/lib/arm64-v8a, /data/app/edu.illinois.rokwire-BuNugcrDly-IakEd8batzw==/split_config.xxxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /system/vendor/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3485)
       at android.app.ActivityThread.access$1200(ActivityThread.java:208)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6991)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by dobromirdobrev** [comment]
Fixed in version 4.1.25
