### ISSUE TITLE
[BUG] Android: Crash in background

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#3941]
**Describe the bug**
There is a reported crash in Crashlytics dashboard for Android. Ref: https://console.firebase.google.com/project/rokwire-mvp01-dev/crashlytics/app/android:edu.illinois.rokwire/issues/cf52267d4ac8dba15c10b9e8c2895c21?time=last-seven-days&types=crash&sessionEventKey=65BD4097004C00014598CEFD75C8ACF6_1909533037133278614

**Expected behavior**
No crash.

**Additional context**
StackTrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {edu.illinois.rokwire/edu.illinois.rokwire.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void ma.i.e(ma.i$c)' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6801)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6847)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:57)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:50)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3059)
       at android.os.Handler.dispatchMessage(Handler.java:117)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:293)
       at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
       at android.app.ActivityThread.main(ActivityThread.java:9923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void ma.i.e(ma.i$c)' on a null object reference
       at edu.illinois.rokwire.mobile_access.MobileAccessPlugin.onDetachedFromEngine(MobileAccessPlugin.java:3)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:121)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:100)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at edu.illinois.rokwire.MainActivity.onDestroy(MainActivity.java)
       at android.app.Activity.performDestroy(Activity.java:8875)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1379)
       at com.vlite.sdk.client.hook.service.app.InstrumentationLiteApp.callActivityOnDestroy(SourceFile:196)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6788)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6847)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:57)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:50)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3059)
       at android.os.Handler.dispatchMessage(Handler.java:117)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:293)
       at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
       at android.app.ActivityThread.main(ActivityThread.java:9923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

FinalizerWatchdogDaemon:
       at java.lang.Thread.sleep(Thread.java)
       at java.lang.Thread.sleep(Thread.java:454)
       at java.lang.Thread.sleep(Thread.java:359)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:390)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:419)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:930)

ReferenceQueueDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:930)

process reaper:
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461)
       at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
       at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:930)

FinalizerDaemon:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:930)
```

**Comment by dobromirdobrev** [comment]
Fixed in. version 5.1.21

**Comment by nienienienie** [comment]
what is at com.vlite.sdk.client.hook.service.app.InstrumentationLiteApp.callActivityOnDestroy(SourceFile:196) in the stack trace?
